### ISSUE TITLE
Add licence 

### ISSUE THREAD

**Issue by debianmaster** [loft-sh/virtual-cluster#1]
Could you please add licence

**Comment by curx** [comment]
+1

**Comment by debianmaster** [comment]
any update?

**Comment by LukasGentele** [comment]
Sorry that it took me a while to add a license. @debianmaster Thanks for the reminder

**Comment by debianmaster** [comment]
@LukasGentele   does this mean, loft is free to use (without node limit) if we use this repo ?   can you clarify

**Comment by LukasGentele** [comment]
The virtual clusters that you can spin up via helm using the chart and using the instructions in the readme of this GitHub repo are, as of today, free to use without any node limits or such. 

For Loft, however, there is a 100 node limit in the free edition. If you hit this limit, shoot me an email (see GH profile) with a few details about your use case. Happy to increase the limit for your instance if necessary, especially for certain types of workloads, such as open source projects and such.

**Comment by debianmaster** [comment]
thanks for the clarification @LukasGentele  !
