### ISSUE TITLE
Error running VirtualCluster in k3s environment

### ISSUE THREAD

**Issue by Mel-Github** [loft-sh/virtual-cluster#4]
Followed the instruction to perform the setup, however at the following step, received error that test-0 not found

`kubectl port-forward test-0 -n virtualcluster 8443:8443`

Not exactly sure hence i decide to try and port forward `virtualcluster-0`

`kubectl port-forward virtualcluster-0 -n virtualcluster 8443:8433`

When i attempt to run z`kubectl --kubeconfig kubeconfig.yaml get namespaces`, encountered timeout

```bash
kubectl port-forward virtualcluster-0 -n virtualcluster 8443:8433
Forwarding from 127.0.0.1:8443 -> 8433
Forwarding from [::1]:8443 -> 8433
Handling connection for 8443
E0310 13:57:55.399419   40380 portforward.go:400] an error occurred forwarding 8443 -> 8433: error forwarding port 8433 to pod 297b1bd6e04a0da810baafe590675d506e20bcb7a3c32a99d7f71ad3c5c02a74, uid : failed to execute portforward in network namespace "/var/run/netns/cni-c5c401e2-e595-ce7d-612d-1ec5d15b28f3": failed to dial 8433: dial tcp4 127.0.0.1:8433: connect: connection refused
Handling connection for 8443
E0310 13:57:56.419330   40380 portforward.go:400] an error occurred forwarding 8443 -> 8433: error forwarding port 8433 to pod 297b1bd6e04a0da810baafe590675d506e20bcb7a3c32a99d7f71ad3c5c02a74, uid : failed to execute portforward in network namespace "/var/run/netns/cni-c5c401e2-e595-ce7d-612d-1ec5d15b28f3": failed to dial 8433: dial tcp4 127.0.0.1:8433: connect: connection refused
Handling connection for 8443
E0310 13:57:57.442891   40380 portforward.go:400] an error occurred forwarding 8443 -> 8433: error forwarding port 8433 to pod 297b1bd6e04a0da810baafe590675d506e20bcb7a3c32a99d7f71ad3c5c02a74, uid : failed to execute portforward in network namespace "/var/run/netns/cni-c5c401e2-e595-ce7d-612d-1ec5d15b28f3": failed to dial 8433: dial tcp4 127.0.0.1:8433: connect: connection refused
Handling connection for 8443
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2+k3s1", GitCommit:"1d4adb0301b9a63ceec8cabb11b309e061f43d5f", GitTreeState:"clean", BuildDate:"2021-01-14T23:52:37Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

However in my other cluster the above steps work perfectly.

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12+rke2r2", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-12-07T21:34:10Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

Is there any requirement that the virtual cluster k3s version must be <= host cluster k3s version?

**Comment by FabianKramm** [comment]
@Mel-Github thanks for opening this issue! Mhh thats odd, could you post the logs of the syncer container within the virtual cluster pod? 

Regarding the versions, it is usually a good idea to have the k3s version the same as the host cluster version, most of the time it will also work across versions, but several features might not work as expected if the virtual cluster k3s version and host cluster version differ. The virtual cluster syncer version should be always the latest available since it is cross version compatible.

**Comment by Mel-Github** [comment]
Hi Fabian

Thanks for the reply. I am unable to recreate the issue. Suddenly the cluster is able to create the virtual. cluster, sorry to cause the confusion.

Can i ask, can a "virtual cluster" in a namespace spawn  another "virtual cluster" ? Is there any limits?

**Comment by FabianKramm** [comment]
@Mel-Github sure, if you find a way to reproduce this issue, please let us know.

Virtual Clusters within virtual clusters are supported and there is no limit how "deep" you can stack them.
